// example/vue/src/pages/TopPage.vue
<template>
  <div style="padding: 20px; max-width: 600px; margin: 0 auto">
    <h1>Colocale Vue Example</h1>
    
    <div style="margin-bottom: 20px">
      <router-link to="/ja/top" style="margin-right: 10px">日本語</router-link>
      <router-link to="/en/top">English</router-link>
    </div>

    <div style="margin-bottom: 20px">
      <label for="nameInput">Name: </label>
      <input
        id="nameInput"
        v-model="inputText"
        type="text"
        placeholder="Enter your name"
        style="padding: 5px; width: 200px"
      />
    </div>

    <div style="font-size: 1.5em; font-weight: bold">
      {{ greeting }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRoute } from 'vue-router'
import { pickMessages, createTranslator, type Locale } from 'colocale'
import { commonTranslations } from '../translations'
import jaCommon from '../../messages/ja/common.json'
import enCommon from '../../messages/en/common.json'

const route = useRoute()
const inputText = ref('')

// Get current locale from route
const locale = computed(() => (route.params.locale as string) || 'en')

// Compose messages
const allMessages = {
  ja: { common: jaCommon },
  en: { common: enCommon },
}

// Pick messages for current locale
const messages = computed(() =>
  pickMessages(allMessages, commonTranslations, locale.value as Locale)
)

// Create translator
const t = computed(() => createTranslator(messages.value, commonTranslations))

// Compute greeting message
const greeting = computed(() =>
  t.value('greeting', { name: inputText.value || 'World' })
)
</script>

// example/react/src/pages/TopPage.tsx
import { useState, useMemo } from "react";
import { useParams, Link } from "react-router-dom";
import { pickMessages, createTranslator, Locale } from "colocale";
import { commonTranslations } from "../translations";
import jaCommon from "../../messages/ja/common.json";
import enCommon from "../../messages/en/common.json";

function TopPage() {
  const { locale = "en" } = useParams<{ locale: string }>();
  const [inputText, setInputText] = useState("");

  // Compose messages
  const allMessages = {
    ja: { common: jaCommon },
    en: { common: enCommon },
  };

  // Pick messages for current locale
  const messages = useMemo(
    () => pickMessages(allMessages, commonTranslations, locale as Locale),
    [locale]
  );

  // Create translator
  const t = createTranslator(messages, commonTranslations);

  return (
    <div style={{ padding: "20px", maxWidth: "600px", margin: "0 auto" }}>
      <h1>Colocale React Example</h1>

      <div style={{ marginBottom: "20px" }}>
        <Link to="/ja/top" style={{ marginRight: "10px" }}>
          日本語
        </Link>
        <Link to="/en/top">English</Link>
      </div>

      <div style={{ marginBottom: "20px" }}>
        <label htmlFor="nameInput">Name: </label>
        <input
          id="nameInput"
          type="text"
          value={inputText}
          onChange={(e) => setInputText(e.target.value)}
          placeholder="Enter your name"
          style={{ padding: "5px", width: "200px" }}
        />
      </div>

      <div style={{ fontSize: "1.5em", fontWeight: "bold" }}>
        {t("greeting", { name: inputText || "World" })}
      </div>
    </div>
  );
}

export default TopPage;
